### ISSUE TITLE
Add External Drive Support

### ISSUE THREAD

**Issue by DefensiveThinking** [g666gle/BaseQuery#1]
Finally I found a application worth my time. Thank you for creating this. I have a question for you. 

I have roughly 10tb of data leaks. They are all stored on a NAS. So if I run this say on a local machine is it going to import those all onto the working machine for indexing or will they stay on the NAS?

**Comment by g666gle** [comment]
So at the moment, BaseQuery can only import from the dedicated folder but since this has been a highly requested feature and I think will improve a lot of functionality and portability I will be working on this very soon and will keep you updated!

**Comment by g666gle** [comment]
Hey @DefensiveThinking I am sorry about the big delay but haven't had the time to work on it. Good news tho! In the past week, I've pretty much re-written all of BaseQuery, including adding the ability to import from an external drive (or anywhere on disk) and export all of the data to somewhere other than BaseQueries default ./data/ directory. Also massive speed improvements on querying, I'm talking over 800X faster : ) So many more features and improvements but you'll have to wait for the full release. Right now the last thing I am finishing up is querying an external ./data/ directory, after that everything should be good and I'll push.

**Comment by g666gle** [comment]
This issue was fixed in the BaseQuery 2.0 release
